### PR TITLE
V1.1.2

### PR DESCRIPTION
**Pull request by PapoutsoglouE**
Clarifications for the use of observation units and samples.
Renamed submission template file.

### CODE REVIEW

**Comment by Anne-Francoise** [comment]
I am globally OK with your propositions with some question though :
- Trials changed in studies : OK but then perhaps, add a synonym or make very clear the equivalence in the study definition.
- DM69 : where does the synonyme « Experimental unit » comes from ? Is it necessary ? It can be ambiguous with the way we name our facilities for doing field experiments…
- DM69 : if you forbid trial in the list (which is consistent with the fact that trials are studies and not observation units) then I think that virtual trial should also be forbidden in the list ?

**Comment by PapoutsoglouE** [comment]
The "experimental unit" synonym comes from MIAPPE 1.0, so I think that it should be kept!  
My understanding about virtual trial was that it was a commonly used term. But I also have nothing against changing it to virtual_study for internal consistency. 

I'm not sure what you mean with the first point. Do you think that we should add "synonym: trial" to the study definition? If so, I think this would create confusion with BrAPI terms, because BrAPI Trial = ISA Investigation.

**Comment by Anne-Francoise** [comment]
_"The "experimental unit" synonym comes from MIAPPE 1.0, so I think that it should be kept!"_ => OK
_"My understanding about virtual trial was that it was a commonly used term. But I also have nothing against changing it to virtual_study for internal consistency."_ => No it is not what I meant. My point was if you forbid "trial" in the list of terms for observation units, then you should also forbid "virtual_trial" because if it is the same level of object (semantically it should?) than trial in the description of an experiment. 
_"I'm not sure what you mean with the first point. Do you think that we should add "synonym: trial" to the study definition? If so, I think this would create confusion with BrAPI terms, because BrAPI Trial = ISA Investigation."_ => OK sorry, I was mistaken

**Comment by PapoutsoglouE** [comment]
>  No it is not what I meant. My point was if you forbid "trial" in the list of terms for observation units, then you should also forbid "virtual_trial" because if it is the same level of object (semantically it should?) than trial in the description of an experiment.

I see what you mean, but is it not a common observation unit type? I know I have seen it in studies @cpommier provided, though I don't exactly understand what it means, in this context. Could either of you explain?

**Comment by cpommier** [comment]
Propositions:
2) DM-71 (Observation unit type) definition:
Type of observation unit in textual form, usually one of the following: block, sub-block, plot, plant, ~~trial~~, study, pot, replication or replicate, individual, ~~virtual_trial~~.  **Use of other observation unit types is possible but not recommended. The observation unit type cannot be used to indicate sub-plant levels. However, observations can still be made on the sub-plant level, as long as the details are indicated in the associated observed variable (see observed variables). Alternatively, it is possible to use samples for more detailed tracing of sub-plant units, attaching the observations to them instead.**

**Comment by PapoutsoglouE** [comment]
If virtual_trials and unit parcels are not commonly used by a larger group of people, then I agree that they should be removed!
I think the rest of the (bold) text is unchanged. Am I missing something?

**Comment by cpommier** [comment]
No that's alright.
I'll do the final review and merge.
Thanks!

**Comment by hcwi** [comment]
I agree that virtual_trials and unit parcels should be explained or removed.

What is meant by an 'individual' ? Presumably something more/else than a 'plant' ?

**Comment by cmiguel21** [comment]
I have only a minor suggestion in the Sample definition to replace “portion of plant tissue” by “plant part” because strictly speaking you can have one or multiple tissues in a sample (or a single cell)

**Comment by cpommier** [comment]
> I agree that virtual_trials and unit parcels should be explained or removed.
> 
> What is meant by an 'individual' ? Presumably something more/else than a 'plant' ?

Well spotted, that's inconsistent too. Let me think about it a few hours. @Anne-Francoise @cmiguel21 , what do you think ?


>
>
>I have only a minor suggestion in the Sample definition to replace “portion of plant tissue” by “plant part” because strictly speaking you can have one or multiple tissues in a sample (or a single cell)

What about  “portion of one or multiple plant tissues”  @cmiguel21  ?

@PapoutsoglouE Could you do a new commit with the modifications we just discussed ?

**Comment by cooperl09** [comment]
> > I agree that virtual_trials and unit parcels should be explained or removed.
I agree with those, as well

> > What is meant by an **'individual'** ? Presumably something more/else than a 'plant' ?
> 
> Well spotted, that's inconsistent too. Let me think about it a few hours. @Anne-Francoise @cmiguel21 , what do you think ?

This also jumped out to me.  I think it is redundant with plant- they both mean an individual plant? Suggest using "whole plant" which is a PO term: PO:0000003 

> > I have only a minor suggestion in the Sample definition to replace **“portion of plant tissue”** by “plant part” because strictly speaking you can have one or multiple tissues in a sample (or a single cell)
> 
> What about “portion of one or multiple plant tissues” @cmiguel21 ?

I would avoid using the **“portion of plant tissue”** (or the plural version above), as that is actually a PO term with a specific meaning: http://browser.planteome.org/amigo/term/PO:0009007.  Rather than replacing with the undefined 'plant part" I suggest using "plant structure" :

http://browser.planteome.org/amigo/term/PO:0009011
id: PO:0009011
name: plant structure
def: "A plant anatomical entity (PO:0025131) that is, or was, part of a plant, or was derived from a part of a plant."

**Comment by PapoutsoglouE** [comment]
Currently, with the latest commit, the recommended observation units are: `block, sub-block, plot, plant, study, pot, replication or replicate, individual`.

I am not familiar with the nuances of each term, but I think it would be a good idea to move towards PO terminology, as per @cooperl09's suggestion.  
Not to nitpick, but would it not be advisable to pick one of `replication or replicate`?

**Comment by Anne-Francoise** [comment]
We should supress "individuals". I think it is used as a synonyme of "Plant", which is clearer.

Going on Laurel Cooper's path:
- I would choose "replication" and it would correspond to AGRO:00000321
- Note that block = AGRO:00000303
- Note that in AGRO_00000301 Agricultural Experimental Plot = Plot in MIAPPE. We could still recommend Plot I believe.
- But then I wonder if we should not get rid (in the recommendations) of sub-block and pot. People can still use it if necessary in their databases but I could not find a recommended term in an ontology...

**Comment by richardostler** [comment]
Apologies for jumping in, I've been following as an interested potential user. 

For our use cases recommended observation units is missing `sub-plot`. In a split-plot design this would be our smallest observation unit for a field experiment. Can you please retain `pot` as a unit for greenhouse/controlled environment studies.

There might be a case for adding `field` but the only good examples I can think of are agronomy and agro-ecological studies, so maybe out of scope for MIAPPE?

For me `replication or replicate`, are confusing as observation units. I understand `replication` to be a statistical method (see AGRO:00000321), not an observation unit, while a `replicate` is a repeated observation unit, rather than a discrete type of observation unit.

**Comment by DanFaria** [comment]
My thoughts:

- On the recommended observation unit levels, they should be (in order): study > plot > block > sub-block > pot > plant
-- 'pot' seems sensible to keep, for greenhouse studies
-- 'individual' we seem to all agree to be a poorer synonym of plant
-- 'trial', 'virtual_trial', 'unit-parsel', I also thing we are all in agreement about
 
- On the definition of sample, I don't think we should stick to a term from PO, because PO doesn't cover the concept of sample---none of the PO terms match the semantics of our concept of sample, which can comprise tissues or cells from one or more parts, as @cmiguel21 stated. That said, we should also avoid defining sample in a way that is very similar to and could be confused with a PO term. I can devote some more thought to a precise and 'safe' definition.

**Comment by PapoutsoglouE** [comment]
I agree with @DanFaria's first point, though if we have to put them in an order, I think it would be more like:  study, block, sub-block, plot, pot, plant.
If sub-plots are commonly used I think they should be added as well.

DM-73, Spatial distribution, is defined as:
`Type and value of a spatial coordinate (georeference or relative) or level of observation (plot 45, subblock 7, block 2) provided as a key-value pair of the form type:value. Levels of observation must be consistent with those listed in the Study section.`.

The field can *include* observation unit types, but it is not limited to them as shown in the example:  
`Latitude:+2.341; row:4 ; X:3; Y:6; Xm:35; Ym:65; Block:1; Plot:894`.

So I think it would be an option to represent the replicate number here as well, in an additional key-value pair. To expand on the example above:  
`Latitude:+2.341; row:4 ; X:3; Y:6; Xm:35; Ym:65; Block:1; Plot:894; replicate: 0`.  
`Latitude:+2.341; row:4 ; X:3; Y:6; Xm:35; Ym:65; Block:1; Plot:894; replicate 1`.  
etc.

> But then I wonder if we should not get rid (in the recommendations) of sub-block and pot. People can still use it if necessary in their databases but I could not find a recommended term in an ontology...

I think that the idea was to have a list of recommended values, but still allow unit types not mentioned in it. I don't see it as a problem if some terms are not represented in any ontologies, and I'm not sure if it is a good reason to restrict MIAPPE because of it. At the same time, it would be an advantage to promote some kind of homogeneity, so that people don't use units outside the list unless they absolutely have to.

@richardostler: The `study` unit type encompasses all units/everything in a study. I believe that the `field` you are proposing would serve the same purpose, or not?  
Thank you for jumping in, community engagement is appreciated!

**Comment by richardostler** [comment]
@PapoutsoglouE @DanFaria For info, I've checked our field experiments database and we have over 30 with a split plot or some other `sub-plot` design. Many of them are also multi-year. So +1 from me for `sub-plot`. By comparison there are only 6 experiments with a `sub-block` in their design. 

> @PapoutsoglouE The study unit type encompasses all units/everything in a study. I believe that the field you are proposing would serve the same purpose, or not?

Yes I think so.

**Comment by DanFaria** [comment]
On the ordering, apologies, I always confuse the order of plot and block. And yes, I think it is good to somehow include an expected order, for the benefit of people like me.

On the issue of things (not) being represented in ontologies, I remind you that we have our own ontology representing MIAPPE (PPEO) where we provide precisely formal definitions of MIAPPE fields (e.g. sample) and of fixed expected values (e.g. the recommended observation levels).
We should (and do) encourage the use of external ontologies as values for MIAPPE fields where such ontologies exist, but for the definitions of the fields themselves, PPEO is and should be the only reference for formal semantics, because a) external ontologies are unlikely to capture our intended semantics exactly and b) it is best to keep formal definitions of MIAPPE terms in one single place. For fields where we want to recommend a fixed list of values that are not formally defined elsewhere, PPEO can (and does) also provide the semantic definitions for them.

**Comment by Anne-Francoise** [comment]
I agree with your final discustion about replicate rather than replication: my mistake! I also agree that we keep important and frequent terms like sub-plot (thank you Richard for your valuable inputs!) but then, as Daniel suggested, lets add them in the PPEO with a proper definition. This is also a very good suggestion.

**Comment by Anne-Francoise** [comment]
Regarding Richard's remark about the term Field below:
"There might be a case for adding field but the only good examples I can think of are agronomy and agro-ecological studies, so maybe out of scope for MIAPPE?"
In the frame of an experiment, what would be the difference between a block and a field? You would tend to name you field "block" when you apply and study the effect of a particular factor/treatment and "field" when you do only observations without applying factors/treatments?
With the cirrent extend of my knowledge, I see no a priori reasons why MIAPPE could not support phenotyping experiments in the scope of agro-ecological studies. However we should probably have a look to the work done by infrastructures supporting experimentations in ecology such as Anaee (https://www.anaee-france.fr/en/infrastructure-services/modelling-and-data/semantic-reference-framework) to avoid misleading duplications and perhaps make a decision/recommendations about the scope of MIAPPE and its best usage.

**Comment by PapoutsoglouE** [comment]
To recap, the following changes will be made in the next commit, unless there is further feedback:

* List of recommended observation units: `study, block, sub-block, plot, sub-plot, pot, whole plant`.
  The `replication/replicate` and the `individual` have been **removed**, and plant has been changed to **whole plant**.

* The example for DM-73, Spatial Distribution, will be changed to **indicate replicates** as well:
`Latitude:+2.341; row:4 ; X:3; Y:6; Xm:35; Ym:65; Block:1; Plot:894; replicate:1`

NOT to be included in this commit: change in the **definition of Sample**, as it needs further consideration.

**Comment by DanFaria** [comment]
Please don't replace 'plant' with 'whole plant', for the following three reasons:

- As I argued above, we should deliberately avoid reusing PO terms, because our scope is different and we do not want confusion (we will have our own definitions in the PPEO).

- 'plant' is already in use in BrAPI

- 'whole plant' has a space, and we are using the observation level to name the ISA assay files, which means we would end up with a file name with a space (not too critical, but to be avoided if possible).

**Comment by cpommier** [comment]
Thanks everybody for this very active discussion! Lets merge it.

**Pull request merged**
